### ISSUE TITLE
IfcZone and IfcSpatialZone

### ISSUE THREAD

**Issue by I-Sokolov** [buildingSMART/IFC_UML#64]
Why do we have both IfcZone and IfcSpatialZone.
It sounds confusing.
If we need both documentation should be more clear what is the difference,

**Comment by TLiebich** [comment]
IfcZone (added in IFC1.0 - or around) is a special group (subtype of IfcGroup) to group spaces. But it did not allow having an own space representation (as often needed for zones), therefore IfcSpatialZone was added later (subtype of IfcSpatialElement). But I agree that we can rationalize this (also in light of the new "late binding" ideas).

**Comment by I-Sokolov** [comment]
Thomas, IfcRelServicesBuildings is deprecated in 4.3 but IfcZone is actual
How to reference IfcZone to spatial structure element?

**Comment by TLiebich** [comment]
Igor, when developing IFC4.3, the functionality of IfcrelSevicesBuildings had been combined into IfcRelReferencedInSpatialStructure, so that any product or system can be referenced in a spatial structure, including the new ones for infrastructure.

see [IfcRelReferencedInSpatialStructure](https://standards.buildingsmart.org/IFC/DEV/IFC4_3/RC1/HTML/link/ifcrelreferencedinspatialstructure.htm)

**Comment by TLiebich** [comment]
Hi Igor - one more comment - these are relevant questions, but would be better asked here:
https://github.com/buildingSMART/IFC4.3.x-development
